# Generated by Django 6.1.1 on 2026-10-04 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='artistas.artista')),
            ],
            options={
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['artista', 'inicio'], name='reserva_res_artista_6e36f5_idx'), models.Index(fields=['estado', 'inicio'], name='reserva_res_estado_6e185c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='reserva_fin_despues_de_inicio')],
            },
        ),
    ]
