# Generated by Django 6.1.1 on 2026-10-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_separar_fecha_y_horas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='reserva_res_artista_16d086_idx',
            old_name='reserva_res_artista_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='reserva_res_estado_867e72_idx',
            old_name='reserva_res_estado_fecha_idx',
        ),
    ]
