# Generated by Django 6.1.1 on 2026-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='artistas/')),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
