# Generated by Django 6.1.1 on 2026-10-04 21:05

from django.db import migrations, models


def copy_specialty_to_styles(apps, schema_editor):
    Artista = apps.get_model('artistas', 'Artista')
    database = schema_editor.connection.alias
    for artista in Artista.objects.using(database).all():
        if artista.especialidad and not artista.estilos:
            artista.estilos = [
                estilo.strip()
                for estilo in artista.especialidad.split(',')
                if estilo.strip()
            ]
            artista.save(using=database, update_fields=['estilos'])


def restore_specialty(apps, schema_editor):
    Artista = apps.get_model('artistas', 'Artista')
    database = schema_editor.connection.alias
    for artista in Artista.objects.using(database).all():
        if artista.estilos:
            artista.especialidad = ', '.join(artista.estilos)
            artista.save(using=database, update_fields=['especialidad'])


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='bio',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='artista',
            name='contacto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='artista',
            name='dias',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='artista',
            name='estilos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artista',
            name='horarios',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(copy_specialty_to_styles, restore_specialty),
        migrations.RemoveField(
            model_name='artista',
            name='especialidad',
        ),
    ]
