# Generated by Django 6.1.1 on 2026-10-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tatuaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('imagen_url', models.CharField(help_text='Ruta estática o URL', max_length=255)),
            ],
        ),
    ]
