# Generated by Django 6.1.1 on 2026-10-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatuaje',
            name='es_disponible',
            field=models.BooleanField(default=False, verbose_name='¿Es un diseño disponible (boceto)?'),
        ),
    ]
